# Generated by Django 5.2.7 on 2025-10-11 07:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220714_0615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headline',
            options={'ordering': ['-created_at'], 'verbose_name': 'Headline', 'verbose_name_plural': 'Headlines'},
        ),
        migrations.AddField(
            model_name='headline',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('business', 'Business'), ('national', 'National'), ('sports', 'Sports'), ('world', 'World'), ('politics', 'Politics'), ('technology', 'Technology'), ('startup', 'Startup'), ('entertainment', 'Entertainment'), ('miscellaneous', 'Miscellaneous')], db_index=True, default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='headline',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='headline',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], db_index=True, default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='headline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='headline',
            name='leaning',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='center', max_length=10),
        ),
        migrations.AlterField(
            model_name='headline',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='headline',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddIndex(
            model_name='headline',
            index=models.Index(fields=['category', 'language'], name='news_headli_categor_8d77d2_idx'),
        ),
        migrations.AddIndex(
            model_name='headline',
            index=models.Index(fields=['created_at'], name='news_headli_created_de0821_idx'),
        ),
    ]
